return {
  ["Controllers"] = "app/Http/Controllers",
  ["Livewire"] = "app/Livewire",
  ["Models"] = "app/Models",
  ["Jobs"] = "app/Jobs",
  ["Views"] = "resources/views",
  ["Migrations"] = "database/migrations",
  ["Providers"] = "app/Providers",
  ["Components"] = "app/View/Components",
  ["Routes"] = "routes",
  ["Factories"] = "database/factories",
  ["Seeders"] = "database/seeders",
  ["Configs"] = "config",
  ["FeatureTest"] = "tests/Feature",
  ["UnitTest"] = "tests/Unit",
  ["Requests"] = "app/Http/Requests",
  ["Policies"] = "app/Policies",
}
