return {
  ["Components"] = "app/View/Components",
  ["Configs"] = "config",
  ["Controllers"] = "app/Http/Controllers",
  ["Events"] = "app/Events",
  ["Factories"] = "database/factories",
  ["FeatureTest"] = "tests/Feature",
  ["Jobs"] = "app/Jobs",
  ["Listeners"] = "app/Listeners",
  ["Livewire"] = "app/Livewire",
  ["Migrations"] = "database/migrations",
  ["Models"] = "app/Models",
  ["Policies"] = "app/Policies",
  ["Providers"] = "app/Providers",
  ["Requests"] = "app/Http/Requests",
  ["Routes"] = "routes",
  ["Seeders"] = "database/seeders",
  ["UnitTest"] = "tests/Unit",
  ["Views"] = "resources/views",
}
