return {
    cast = "app/Casts",
    channel = "app/Broadcasting",
    command = "app/Console/Commands",
    component = "app/View/Components",
    controller = "app/Http/Controllers",
    event = "app/Events",
    exception = "app/Exceptions",
    factory = "database/factories",
    job = "app/Jobs",
    listener = "app/Listeners",
    mail = "app/Mail",
    middleware = "app/Http/Middleware",
    migration = "database/migrations",
    model = "app/Models",
    notification = "app/Notifications",
    observer = "app/Observers",
    policy = "app/Policies",
    provider = "app/Providers",
    request = "app/Http/Requests",
    resource = "app/Http/Resources",
    rule = "app/Rules",
    scope = "app/Models/Scopes",
    seeder = "database/seeders",
    test = "tests/Feature",
}
